### ISSUE TITLE
deploy no longer works - prompts apache page and not guac

### ISSUE THREAD

**Issue by itpick** [aries-strato/guacamole-aws#1]
deploy no longer works - prompts apache page and not guac
I suspect the latest guac needs to be deployed differently then your current deploy scripts.

**Comment by itpick** [comment]
To correct I had to rerun the mysql init scripts directly on the database.

**Comment by ariesyous** [comment]
I run the MySQL init scripts from the jump server, are you using RDS or did you roll your own DB server on an EC2 instance?
